-- TO CREATE EACH TABLE IN THE IOTBAY DATABASE, RIGHT CLICK ON 'TABLES' AND CLICK ‘EXECUTE COMMAND’ THEN COPY AND PASTE THE FOLLOWING SQL QUERIES:

-- Create USERS table:
CREATE TABLE USERS (EMAIL VARCHAR(50) NOT NULL, "NAME" VARCHAR(50), PASSWORD VARCHAR(20), GENDER VARCHAR(20), ADDRESS VARCHAR(50), PRIMARY KEY (EMAIL));

-- Create CUSTOMERS table:

-- Create ORDERS table:

-- Create ORDERLINES table:

-- Create DEVICES table:

-- Create PAYMENTMETHODS table:

-- Create PRODUCTCATEGORIES table:

-- Set up FOREIGNKEYS
